project:
  type: site
  output-dir: docs

site:
  title: "BiG Workflow"
  navbar:
    type: dark
    background: gold
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    right:
      - icon: github
        href: https://github.com/JulianTao/bigworkflow
  sidebar:
    style: "docked"
    search: true
    contents:
      - git.qmd
      - gd.qmd
      - documentation.qmd
      - knowledge.qmd
      - lab.qmd
      - agave-template.qmd
format:
  html:
    theme: cosmo
    linkcolor: maroon
    highlight-style: github
    css: styles.css
    toc: true
